version: "3"

tasks:
  cluster-create:
    desc: Crée un kind cluster et déploie l'application
    cmds:
      - task: cluster-create-kind
      - task: wait-cluster-ready
      - task: load-docker-image
      - task: install-nginx-gateway
      - task: install-atlas-operator
      - task: deploy-app
      - echo "Fin du Déploiement"

  cluster-create-kind:
    desc: Creates a kind cluster
    cmds:
      - cmd: kind create cluster --config ./kubernetes/kind.yaml
    internal: true

  wait-cluster-ready:
    desc: Attend que le cluster soit prêt
    cmds:
      - kubectl wait --for=condition=Ready nodes --all --timeout=120s
      - kubectl wait --for=condition=Ready pods -n kube-system -l k8s-app=kube-dns --timeout=120s
    internal: true

  load-docker-image:
    desc: Charge l'image Docker locale dans le cluster Kind
    cmds:
      - |
        IMAGE_NAME="ghcr.io/naqa92/todolist:latest"
        echo "Loading Docker image: $IMAGE_NAME"
        kind load docker-image "$IMAGE_NAME"
    internal: true

  install-nginx-gateway:
    desc: Installe NGINX Gateway Fabric avec les CRDs du Gateway API
    cmds:
      - kubectl kustomize https://github.com/nginx/nginx-gateway-fabric/config/crd/gateway-api/standard?ref=v2.2.0 | kubectl apply -f -
      - helm install ngf oci://ghcr.io/nginx/charts/nginx-gateway-fabric --create-namespace -n nginx-gateway -f ./kubernetes/nginx-values.yaml
      - kubectl -n nginx-gateway wait --for=condition=Available deployment/nginx-gateway
    internal: true

  install-atlas-operator:
    desc: Installe l'Atlas Operator pour gérer les migrations de base de données
    cmds:
      - helm install atlas-operator oci://ghcr.io/ariga/charts/atlas-operator -n atlas-operator --create-namespace
      - kubectl -n atlas-operator wait --for=condition=Available deployment/atlas-operator
    internal: true

  deploy-app:
    desc: Déploie l'application dans le cluster
    cmds:
      - kubectl create namespace demo
      - |
        kubectl -n demo create secret generic db-app \
          --from-literal=host="${DATABASE_HOST}" \
          --from-literal=password="${DATABASE_PASSWORD}" \
          --from-literal=uri="${DATABASE_URL}"
      - kubectl -n demo apply -f ./kubernetes/AtlasSchema.yaml
      - kubectl -n demo wait --for=condition=Ready atlasschema/todos --timeout=120s
      - kubectl -n demo apply -f ./kubernetes/todolist
      - kubectl -n demo wait --for=condition=Ready pod -l app.kubernetes.io/name=todolist --timeout=120s
      - echo "Attente de la configuration du Gateway API..."
      - |
        for i in {1..30}; do
          if curl -sf http://todolist.127.0.0.1.sslip.io/ > /dev/null 2>&1; then
            echo "✓ Application accessible via le Gateway API"
            exit 0
          fi
          echo "Tentative $i/30 - En attente du Gateway API..."
          sleep 2
        done
        echo "L'accès à todolist.127.0.0.1.sslip.io a échoué après 30 tentatives"
        exit 1
    internal: true
